apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      name: mongo
      targetPort: 27017
      protocol: TCP
  clusterIP: None
  selector:
    name: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        name: mongo
    spec:
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip"
          - 0.0.0.0
          - "--smallfiles"
          - "--noprealloc"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-nfs
          mountPath: /data/db
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: mongo-nfs
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 100Mi
      selector:
        matchLabels:
          type: nfs
