kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-nfs-mongo-2
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /root/nfsvol
    server: 192.168.1.181

	